---
- hosts: gclaudio
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - git
        - python3
        - python3-pip
    
    - name: Add Docker GPG KEY
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add DOcker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian {{ ansible_distribution_release | lower }} stable
        state: present
    
    - name: Install docker
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    
    - name: Verify if docker is active
      service:
        name: docker
        state: started
        enabled: yes

    - name: Clone the Github repository
      git:
        repo: https://github.com/kamuridesu/kamublog.git
        dest: /home/{{ lookup('env', 'USER') }}/git
        clone: yes
        update: yes
        version: main

  handlers:
    - name: restart docker
      service: 
        name: docker 
        state: restarted